### ISSUE TITLE
Fix animated GIF

### ISSUE THREAD

**Issue by rogerhu** [sdonnelly-hearsay/TodoProject#1]
I don't see an animated GIF in this project.

Have time to try any of the other optionals?

**Comment by sdonnelly-hearsay** [comment]
Should be fixed now, copied the wrong imgur link! I'll give one or two of the other optionals a go again tonight.

**Comment by sdonnelly-hearsay** [comment]
How do we feel about me switching to using Kotlin for this? I'd prefer to get as much practice with it as possible. Though if it's going to be an issue on group projects later, I can stay away.
